[pytest]
testpaths = tests
norecursedirs =
    .git
    .cache
    .venv
    data
    dxevolve-nature-latex
    external_repos
    logs
    outputs
    pmlb
    reports
    runs
    srbench
    srsd-benchmark
