model:
  kwargs:
    population_size: 1500
    stack_size: 48
    operators:
      - "+"
      - "-"
      - "*"
      - "/"
      - sin
      - cos
      - exp
      - log
      - sqrt
    use_simplification: true
    crossover_prob: 0.35
    mutation_prob: 0.45
    metric: mse
    clo_alg: lm
    clo_threshold: 1.0e-8
    max_time: 21600
    max_evals: 3000000
    evolutionary_algorithm: AgeFitnessEA
data:
  max_train_rows: 10000
runtime:
  max_fit_seconds: 21720
