model:
  output_dir: './gplearn_medium_1thread/'
  kwargs:
    population_size: 800
    generations: 40
    stopping_criteria: 1.0e-8
    const_range: !!python/tuple [-10.0, 10.0]
    p_crossover: 0.7
    p_subtree_mutation: 0.1
    p_hoist_mutation: 0.05
    p_point_mutation: 0.1
    warm_start: False
    max_samples: 0.9
    verbose: False
    parsimony_coefficient: 0.005
    function_set: ['add', 'sub', 'mul', 'div', 'sqrt', 'sin', 'cos', 'log', 'exp']
    n_jobs: 1
data:
  max_train_rows: 2000
runtime:
  max_fit_seconds: 300
