data:
  max_train_rows: 10000

runtime:
  max_fit_seconds: 21600

model:
  kwargs:
    gens: 900
    popsize: 240
    expolim: [-4, 4]
    max_terms: 8
    fitness_f: rmse
    simplify_method: null
    random_state: 42
    verbose: false
    tfuncs: ['id', 'sin', 'cos', 'log', 'exp', 'sqrt']
