model:
  kwargs:
    gens: 160
    popsize: 160
    expolim: [-3, 3]
    max_terms: 8
    fitness_f: rmse
    simplify_method: simplify_by_var
    random_state: 42
    verbose: false
    tfuncs: ['id', 'sin', 'cos', 'exp', 'log', 'sqrt']
runtime:
  max_fit_seconds: 100
