model:
  kwargs:
    population_size: 1200
    generations: 360
    max_length: 50
    max_depth: 15
    max_time: 570
    n_threads: 1
    objectives: ['r2', 'length']
    allowed_symbols: 'add,sub,mul,div,sqrt,log,exp,sin,cos,constant,variable'
    epsilon: 1.0e-7
    reinserter: 'keep-best'
    offspring_generator: 'basic'
    optimizer_iterations: 30
    optimizer: 'lm'
    max_evaluations: 4000000
    tournament_size: 4
    random_state: 42
data:
  max_train_rows: 3000
runtime:
  max_fit_seconds: 600
