fit:
  procs: 3
  populations: 9
  population_size: 160
  ncyclesperiteration: 400
  niterations: 3600
  timeout_in_seconds: 21600
  maxsize: 60
  binary_operators: ['+', '-', '*', '/']
  unary_operators: ['sin', 'cos', 'exp', 'log', 'sqrt']
  nested_constraints:
    sin:
      sin: 0
      cos: 0
    cos:
      sin: 0
      cos: 0
    exp:
      exp: 0
    log:
      log: 0
    sqrt:
      sqrt: 0
  progress: false
  weight_randomize: 0.15
  precision: 32
  warm_start: false
  turbo: true
  update: false
  model_selection: best
