data:
  max_train_rows: 5000

fit:
  procs: 1
  populations: 4
  population_size: 60
  ncyclesperiteration: 80
  niterations: 80
  timeout_in_seconds: 120
  maxsize: 32
  binary_operators: ['+', '-', '*', '/']
  unary_operators: ['sin', 'cos', 'exp', 'log', 'sqrt']
  nested_constraints:
    sin:
      sin: 0
      cos: 0
    cos:
      sin: 0
      cos: 0
    exp:
      exp: 0
    log:
      log: 0
    sqrt:
      sqrt: 0
  progress: false
  weight_randomize: 0.15
  precision: 32
  warm_start: false
  turbo: true
  update: false
  model_selection: best
