model:
  kwargs:
    max_fit_calls: 20000
    max_time: 120
    complexity_penalty: 0.0005
    max_complexity: 60
    sample_size: 0
    verbose: false
data:
  max_train_rows: 2000
runtime:
  max_fit_seconds: 150
