model:
  kwargs:
    population_size: 500
    generations: 120
    max_length: 35
    max_depth: 12
    max_time: 180
    n_threads: 4
    objectives: ['r2', 'length']
    allowed_symbols: 'add,sub,mul,div,sqrt,log,exp,sin,cos,constant,variable'
    epsilon: 1.0e-5
    reinserter: 'keep-best'
    offspring_generator: 'basic'
    optimizer_iterations: 10
    optimizer: 'lm'
    max_evaluations: 1000000
    tournament_size: 3
    random_state: 42
