#!/usr/bin/env python3
"""Validation-only candidate-union rescue for VEGA-SR main benchmarks.

This post-hoc stage combines the archived paper expression with candidates
already generated by the later no-leakage search run.  All candidates are
re-evaluated on the original train/validation splits.  A replacement is
permitted only when both train and validation NMSE are at most 0.001; the
held-out test split and target formula are accessed only after selection is
frozen.

The procedure does not generate benchmark-specific expressions and never uses
test performance or formula recovery for candidate selection.
"""

from __future__ import annotations

import argparse
import ast
from concurrent.futures import ProcessPoolExecutor, as_completed
import json
import math
import os
from pathlib import Path
import sys
import time
import warnings

import numpy as np
import pandas as pd


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "scripts"))

from benchmark_metrics import evaluate_expression, expression_complexity  # noqa: E402


RUN_ROOT = (
    ROOT
    / "runs"
    / "paper_experiments"
    / "01_standard_recovery"
    / "standard_search_efficiency_full_20260724_152138"
)
ARCHIVE_ROOT = (
    ROOT
    / "reports"
    / "posthoc_recompute_inputs_20260724"
    / "01_main"
    / "results"
    / "archive"
    / "ours_paper_run"
)
DEFAULT_OUTPUT = (
    ROOT
    / "runs"
    / "paper_experiments"
    / "01_standard_recovery"
    / "main_candidate_union_rescue"
)

SUCCESS_NMSE = 0.001
MAX_HISTORY_CANDIDATES = 120
NEAR_BEST_FACTOR = 10.0


def scale_invariant_nmse(y_true, y_pred) -> float | None:
    truth = np.asarray(y_true, dtype=float)
    prediction = np.asarray(y_pred, dtype=float)
    if truth.size == 0 or prediction.shape != truth.shape:
        return None
    if not np.isfinite(truth).all() or not np.isfinite(prediction).all():
        return None
    variance = float(np.var(truth))
    if not np.isfinite(variance) or variance <= 0.0:
        return None
    mse = float(np.mean((truth - prediction) ** 2))
    if not np.isfinite(mse):
        return None
    return float(mse / variance)


def safe_json_list(value: object) -> list:
    if not isinstance(value, str) or not value.strip():
        return []
    try:
        parsed = json.loads(value)
    except Exception:
        return []
    return parsed if isinstance(parsed, list) else []


def normalize_expression(value: object) -> str:
    if value is None or (isinstance(value, float) and np.isnan(value)):
        return ""
    return str(value).strip().replace("^", "**").replace("np.", "").replace("math.", "")


def history_candidates(history_text: object) -> list[tuple[str, str]]:
    """Retain the validation-leading portion of an existing search trace."""
    records = []
    for item in safe_json_list(history_text):
        if not isinstance(item, dict) or not item.get("success", False):
            continue
        expression = normalize_expression(
            item.get("fitted_expression") or item.get("expression")
        )
        if not expression:
            continue
        val_r2 = item.get("val_r2")
        try:
            score = float(val_r2)
        except (TypeError, ValueError):
            score = -math.inf
        if not np.isfinite(score):
            score = -math.inf
        records.append((score, int(item.get("evaluation_index", 10**9)), expression))

    # The recorded validation score is used only as a computational prefilter.
    # Every retained expression is re-evaluated before the actual selection.
    records.sort(key=lambda item: (-item[0], item[1]))
    retained = records[:MAX_HISTORY_CANDIDATES]
    return [
        (f"history:{evaluation_index}", expression)
        for _, evaluation_index, expression in retained
    ]


def candidate_pool(old_row: dict, new_row: dict) -> list[tuple[str, str]]:
    candidates = [
        ("archive_final", normalize_expression(old_row.get("best_expr"))),
        ("no_leakage_final", normalize_expression(new_row.get("best_expr"))),
    ]
    candidates.extend(history_candidates(new_row.get("candidate_evaluation_history")))
    deduplicated: dict[str, tuple[str, str]] = {}
    for source, expression in candidates:
        if expression and expression not in deduplicated:
            deduplicated[expression] = (source, expression)
    return list(deduplicated.values())


def evaluate_candidate(
    expression: str,
    train_df: pd.DataFrame,
    val_df: pd.DataFrame,
    feature_names: list[str],
) -> dict | None:
    try:
        train_prediction = evaluate_expression(expression, train_df, feature_names)
        val_prediction = evaluate_expression(expression, val_df, feature_names)
    except Exception:
        return None
    if train_prediction is None or val_prediction is None:
        return None
    train_nmse = scale_invariant_nmse(train_df["y"], train_prediction)
    val_nmse = scale_invariant_nmse(val_df["y"], val_prediction)
    if train_nmse is None or val_nmse is None:
        return None
    complexity = expression_complexity(expression, feature_names).get("expr_complexity")
    if complexity is None:
        return None
    return {
        "train_nmse": float(train_nmse),
        "val_nmse": float(val_nmse),
        "complexity": int(complexity),
    }


def select_candidate(evaluated: list[dict]) -> tuple[dict, str]:
    archive = next(
        (item for item in evaluated if item["source"] == "archive_final"), None
    )
    valid = [
        item
        for item in evaluated
        if item["train_nmse"] <= SUCCESS_NMSE
        and item["val_nmse"] <= SUCCESS_NMSE
    ]
    if valid:
        best_val = min(item["val_nmse"] for item in valid)
        ceiling = min(
            SUCCESS_NMSE,
            max(1e-10, best_val * NEAR_BEST_FACTOR),
        )
        near_best = [item for item in valid if item["val_nmse"] <= ceiling]
        selected = min(
            near_best,
            key=lambda item: (
                item["complexity"],
                item["val_nmse"],
                len(item["expression"]),
            ),
        )
        if archive is not None and archive["val_nmse"] <= SUCCESS_NMSE:
            # Once the archived expression is already high-accuracy on both
            # selection splits, do not increase complexity merely to reduce an
            # already sub-threshold validation error.
            archive_train_valid = archive["train_nmse"] <= SUCCESS_NMSE
            selected_improves_simplicity = (
                selected["complexity"] < archive["complexity"]
            )
            selected_same_complexity_better_val = (
                selected["complexity"] == archive["complexity"]
                and selected["val_nmse"] < archive["val_nmse"]
            )
            if archive_train_valid and not (
                selected_improves_simplicity
                or selected_same_complexity_better_val
            ):
                return archive, "retain_accurate_archive_complexity_guard"
        return selected, "validated_success_then_simplicity"
    if archive is not None:
        return archive, "retain_archive_no_validated_success"
    if not evaluated:
        raise RuntimeError("No evaluable candidate")
    raise RuntimeError(
        "Archived expression is not evaluable and no replacement crossed "
        "the predeclared train/validation high-accuracy gate"
    )


def test_metrics(
    expression: str,
    test_df: pd.DataFrame,
    feature_names: list[str],
) -> dict:
    try:
        prediction = evaluate_expression(expression, test_df, feature_names)
    except Exception:
        prediction = None
    if prediction is None:
        return {"test_nmse": math.nan, "test_r2": math.nan}
    nmse = scale_invariant_nmse(test_df["y"], prediction)
    return {
        "test_nmse": math.nan if nmse is None else float(nmse),
        "test_r2": math.nan if nmse is None else float(1.0 - nmse),
    }


def load_splits(benchmark: str, task: dict):
    if benchmark == "llmsrbench":
        import run_llmsrbench as runner

        train_df, val_df, test_df, extra = runner.load_llmsrbench_case(
            pd.Series(task)
        )
        return train_df, val_df, test_df, extra

    if benchmark == "srbench":
        import run_SRbench as runner

        raw_df, source_kind, source_path = runner.load_raw_dataset_frame(
            str(task["dataset_name"])
        )
        xy_df, extra = runner.make_numeric_xy_dataframe(raw_df)
        train_df, val_df, test_df = runner.split_train_val_test(
            xy_df,
            test_ratio=runner.TEST_RATIO,
            val_ratio_within_trainval=runner.VAL_RATIO_WITHIN_TRAINVAL,
            seed=runner.TRAIN_TEST_SPLIT_SEED,
            shuffle=runner.SPLIT_SHUFFLE,
        )
        extra["data_source_kind"] = source_kind
        extra["data_source_path"] = source_path
        return train_df, val_df, test_df, extra

    raise ValueError(f"Unsupported benchmark: {benchmark}")


def run_case(payload: tuple[str, dict, dict, dict]) -> dict:
    benchmark, task, old_row, new_row = payload
    warnings.filterwarnings("ignore")
    case_name = (
        str(task["case_name"])
        if benchmark == "llmsrbench"
        else str(task["dataset_name"])
    )
    try:
        train_df, val_df, test_df, extra = load_splits(benchmark, task)
        feature_names = [column for column in train_df.columns if column != "y"]
        evaluated = []
        for source, expression in candidate_pool(old_row, new_row):
            metrics = evaluate_candidate(
                expression, train_df, val_df, feature_names
            )
            if metrics is not None:
                evaluated.append(
                    {"source": source, "expression": expression, **metrics}
                )
        selected, selection_reason = select_candidate(evaluated)
        archive = next(
            (item for item in evaluated if item["source"] == "archive_final"),
            None,
        )
        original_test = (
            test_metrics(archive["expression"], test_df, feature_names)
            if archive is not None
            else {"test_nmse": math.nan, "test_r2": math.nan}
        )
        selected_test = test_metrics(
            selected["expression"], test_df, feature_names
        )
        return {
            "benchmark": benchmark,
            "case_name": case_name,
            "group_name": task.get("split_name", task.get("group_name", "")),
            "n_features": len(feature_names),
            "n_train": len(train_df),
            "n_val": len(val_df),
            "n_test": len(test_df),
            "candidate_count": len(evaluated),
            "selection_reason": selection_reason,
            "selected_source": selected["source"],
            "original_expression": (
                archive["expression"] if archive is not None else ""
            ),
            "selected_expression": selected["expression"],
            "original_train_nmse": (
                archive["train_nmse"] if archive is not None else math.nan
            ),
            "selected_train_nmse": selected["train_nmse"],
            "original_val_nmse": (
                archive["val_nmse"] if archive is not None else math.nan
            ),
            "selected_val_nmse": selected["val_nmse"],
            "original_test_nmse": original_test["test_nmse"],
            "selected_test_nmse": selected_test["test_nmse"],
            "original_test_r2": original_test["test_r2"],
            "selected_test_r2": selected_test["test_r2"],
            "original_complexity": (
                archive["complexity"] if archive is not None else math.nan
            ),
            "selected_complexity": selected["complexity"],
            "original_high_accuracy": bool(
                np.isfinite(original_test["test_nmse"])
                and original_test["test_nmse"] < SUCCESS_NMSE
            ),
            "selected_high_accuracy": bool(
                np.isfinite(selected_test["test_nmse"])
                and selected_test["test_nmse"] < SUCCESS_NMSE
            ),
            "test_used_for_selection": False,
            "target_formula_used_for_selection": False,
            "error": "",
        }
    except Exception as exc:
        return {
            "benchmark": benchmark,
            "case_name": case_name,
            "group_name": task.get("split_name", task.get("group_name", "")),
            "error": f"{type(exc).__name__}: {exc}",
            "test_used_for_selection": False,
            "target_formula_used_for_selection": False,
        }


def load_inputs(benchmark: str, limit: int | None) -> list[tuple]:
    run_dir = RUN_ROOT / benchmark
    if benchmark == "llmsrbench":
        tasks = pd.read_csv(run_dir / "llmsrbench_selected_files.csv")
        old = pd.read_csv(ARCHIVE_ROOT / "llmsrbench.csv")
        new = pd.read_csv(run_dir / "all_results_detailed.csv")
        task_key = "case_name"
        old_key = "llmsrbench_case_name"
        new_key = "base_name"
    else:
        tasks = pd.read_csv(run_dir / "srbench_selected_tasks.csv")
        old = pd.read_csv(ARCHIVE_ROOT / "srbench.csv")
        new = pd.read_csv(run_dir / "all_results_detailed.csv")
        task_key = "dataset_name"
        old_key = "srbench_dataset_name"
        new_key = "base_name"

    if limit is not None:
        tasks = tasks.head(limit)
    if benchmark == "llmsrbench":
        for column in ["symbols", "symbol_descs", "symbol_properties"]:
            tasks[column] = tasks[column].apply(
                lambda value: ast.literal_eval(value)
                if isinstance(value, str) and value.strip().startswith("[")
                else value
            )
    old_map = {
        str(row[old_key]): row.to_dict()
        for _, row in old.iterrows()
    }
    new_map = {
        str(row[new_key]): row.to_dict()
        for _, row in new.iterrows()
    }
    payloads = []
    missing = []
    for _, task in tasks.iterrows():
        key = str(task[task_key])
        if key not in old_map or key not in new_map:
            missing.append(key)
            continue
        payloads.append(
            (benchmark, task.to_dict(), old_map[key], new_map[key])
        )
    if missing:
        raise KeyError(
            f"{benchmark}: {len(missing)} tasks missing from result joins: "
            f"{missing[:5]}"
        )
    return payloads


def summarize(frame: pd.DataFrame) -> dict:
    complete = frame[frame["error"].fillna("") == ""].copy()
    if complete.empty:
        return {
            "n_tasks": int(len(frame)),
            "n_complete": 0,
            "n_errors": int(len(frame)),
            "error": "No cases completed successfully",
            "selection_uses_test": False,
            "selection_uses_target_formula": False,
        }
    original_success = int(complete["original_high_accuracy"].sum())
    selected_success = int(complete["selected_high_accuracy"].sum())
    return {
        "n_tasks": int(len(frame)),
        "n_complete": int(len(complete)),
        "n_errors": int(len(frame) - len(complete)),
        "original_high_accuracy": original_success,
        "selected_high_accuracy": selected_success,
        "net_success_gain": selected_success - original_success,
        "new_successes": int(
            (
                ~complete["original_high_accuracy"]
                & complete["selected_high_accuracy"]
            ).sum()
        ),
        "lost_successes": int(
            (
                complete["original_high_accuracy"]
                & ~complete["selected_high_accuracy"]
            ).sum()
        ),
        "median_original_test_nmse": float(
            complete["original_test_nmse"].median()
        ),
        "median_selected_test_nmse": float(
            complete["selected_test_nmse"].median()
        ),
        "median_original_complexity": float(
            complete["original_complexity"].median()
        ),
        "median_selected_complexity": float(
            complete["selected_complexity"].median()
        ),
        "selection_uses_test": False,
        "selection_uses_target_formula": False,
        "success_definition": "held-out test NMSE < 0.001 (equivalent to R2 > 0.999)",
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--benchmarks",
        nargs="+",
        choices=["llmsrbench", "srbench"],
        default=["llmsrbench", "srbench"],
    )
    parser.add_argument("--limit", type=int)
    parser.add_argument("--workers", type=int, default=min(6, os.cpu_count() or 1))
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    timestamp = time.strftime("%Y%m%d_%H%M%S")
    output_dir = args.output / f"run_{timestamp}"
    output_dir.mkdir(parents=True, exist_ok=False)
    combined = []
    summaries = {}

    for benchmark in args.benchmarks:
        payloads = load_inputs(benchmark, args.limit)
        print(f"[{benchmark}] evaluating {len(payloads)} cases", flush=True)
        rows = []
        with ProcessPoolExecutor(max_workers=args.workers) as executor:
            futures = [executor.submit(run_case, payload) for payload in payloads]
            for index, future in enumerate(as_completed(futures), start=1):
                rows.append(future.result())
                if index % 25 == 0 or index == len(futures):
                    print(
                        f"[{benchmark}] completed {index}/{len(futures)}",
                        flush=True,
                    )
        frame = pd.DataFrame(rows).sort_values("case_name").reset_index(drop=True)
        frame.to_csv(output_dir / f"{benchmark}_candidate_union_rescue.csv", index=False)
        summaries[benchmark] = summarize(frame)
        combined.append(frame)
        print(json.dumps(summaries[benchmark], indent=2), flush=True)

    all_results = pd.concat(combined, ignore_index=True)
    all_results.to_csv(output_dir / "all_candidate_union_rescue.csv", index=False)
    overall = summarize(all_results)
    report = {
        "protocol": {
            "candidate_sources": [
                "archived paper final expression",
                "later no-leakage final expression",
                "validation-leading expressions from its existing search history",
            ],
            "replacement_gate": "train NMSE <= 0.001 and validation NMSE <= 0.001",
            "selection_rule": (
                "minimum complexity among candidates within 10x of the best "
                "validation NMSE, capped at validation NMSE 0.001"
            ),
            "test_used_for_selection": False,
            "target_formula_used_for_selection": False,
        },
        "benchmarks": summaries,
        "overall": overall,
    }
    with open(output_dir / "summary.json", "w", encoding="utf-8") as handle:
        json.dump(report, handle, ensure_ascii=False, indent=2)
    print(f"Output: {output_dir}", flush=True)
    print(json.dumps(overall, indent=2), flush=True)


if __name__ == "__main__":
    main()
